"use strict";

const EMAIL_TIERS = Object.freeze({
  TIER_1: "tier1",
  TIER_2: "tier2",
  TIER_3: "tier3",
});

const freezePayloadContract = (payload = {}) =>
  Object.freeze({
    required: Object.freeze([...(payload.required || [])]),
    optional: Object.freeze([...(payload.optional || [])]),
  });

const defineEntry = ({
  tier,
  audience,
  category,
  trigger,
  implemented,
  live,
  payload,
}) =>
  Object.freeze({
    tier,
    audience,
    category,
    trigger,
    implemented: Boolean(implemented),
    live: Boolean(live),
    payload: freezePayloadContract(payload),
  });

// Email template catalog and payload contracts.
// Contracts describe the expected payload keys accepted by each template builder.
const EMAIL_TEMPLATE_CATALOG = Object.freeze({
  "password-reset": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "auth",
    trigger: "User requests password reset.",
    implemented: true,
    live: true,
    payload: {
      required: ["resetUrl"],
      optional: ["expiresInMinutes"],
    },
  }),
  "welcome-account": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "auth",
    trigger: "New account is created.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: ["appUrl", "loginUrl"],
    },
  }),
  "email-verification": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "auth",
    trigger: "User must verify account email.",
    implemented: true,
    live: true,
    payload: {
      required: ["verificationUrl"],
      optional: ["customerName", "expiresInMinutes"],
    },
  }),
  "partner-account-approved": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "onboarding",
    trigger: "Partner account request is approved.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: ["accountName", "loginUrl", "dashboardUrl", "appUrl"],
    },
  }),
  "partner-account-rejected": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "onboarding",
    trigger: "Partner account request is rejected.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: ["accountName", "rejectionReason", "reason", "supportUrl", "appUrl"],
    },
  }),
  "artist-access-request-received": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "onboarding",
    trigger: "Artist access request is submitted.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: [
        "applicantName",
        "requestReference",
        "submittedAt",
        "reviewStatus",
        "dashboardUrl",
      ],
    },
  }),
  "artist-access-request-approved": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "onboarding",
    trigger: "Artist access request is approved.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: [
        "applicantName",
        "artistName",
        "requestReference",
        "loginUrl",
        "dashboardUrl",
        "setupUrl",
      ],
    },
  }),
  "artist-access-request-rejected": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "onboarding",
    trigger: "Artist access request is rejected.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: [
        "applicantName",
        "requestReference",
        "rejectionReason",
        "reason",
        "reapplyUrl",
        "supportUrl",
      ],
    },
  }),
  "order-confirmation": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "orders",
    trigger: "Order is created successfully.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: [
        "customerName",
        "orderNumber",
        "orderId",
        "orderReference",
        "orderDate",
        "currency",
        "items",
        "itemCount",
        "subtotalCents",
        "subtotal",
        "shippingCents",
        "shipping",
        "discountCents",
        "discount",
        "totalCents",
        "total",
        "shippingAddress",
        "orderUrl",
      ],
    },
  }),
  "order-status-processing": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "orders",
    trigger: "Order transitions to processing.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: [
        "customerName",
        "orderNumber",
        "orderId",
        "orderReference",
        "orderDate",
        "currency",
        "orderStatus",
        "items",
        "subtotalCents",
        "shippingCents",
        "discountCents",
        "totalCents",
        "shippingAddress",
        "orderUrl",
      ],
    },
  }),
  "order-status-shipped": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "shipping",
    trigger: "Order is shipped.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: [
        "customerName",
        "orderNumber",
        "orderId",
        "orderReference",
        "orderDate",
        "currency",
        "items",
        "subtotalCents",
        "shippingCents",
        "discountCents",
        "totalCents",
        "shippingAddress",
        "trackingUrl",
        "trackingNumber",
        "carrier",
        "orderUrl",
      ],
    },
  }),
  "order-status-delivered": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "shipping",
    trigger: "Order is delivered.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: [
        "customerName",
        "orderNumber",
        "orderId",
        "orderReference",
        "orderDate",
        "currency",
        "items",
        "subtotalCents",
        "shippingCents",
        "discountCents",
        "totalCents",
        "shippingAddress",
        "orderUrl",
      ],
    },
  }),
  "order-status-cancelled": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "orders",
    trigger: "Order is cancelled.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: [
        "customerName",
        "orderNumber",
        "orderId",
        "orderReference",
        "orderDate",
        "currency",
        "items",
        "subtotalCents",
        "shippingCents",
        "discountCents",
        "totalCents",
        "shippingAddress",
        "orderUrl",
      ],
    },
  }),
  "order-status-refunded": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "payments",
    trigger: "Order refund is issued.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: [
        "customerName",
        "orderNumber",
        "orderId",
        "orderReference",
        "orderDate",
        "currency",
        "items",
        "subtotalCents",
        "shippingCents",
        "discountCents",
        "totalCents",
        "shippingAddress",
        "orderUrl",
      ],
    },
  }),
  "drop-quiz-lead-thank-you": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "engagement",
    trigger: "Lead submits drop quiz/contact details.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: ["customerName", "dropName", "artistName", "dropUrl", "followUpWindowHours"],
    },
  }),
  "contact-form-received": defineEntry({
    tier: EMAIL_TIERS.TIER_2,
    audience: "customer",
    category: "support",
    trigger: "Contact/support form is submitted.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: ["customerName", "ticketId", "submittedAt", "supportUrl"],
    },
  }),
  "admin-notify-new-artist-access-request": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "internal",
    category: "operations",
    trigger: "Notify admins when new artist access request arrives.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: [
        "applicantName",
        "artistName",
        "labelName",
        "requestReference",
        "submittedAt",
        "requesterEmail",
        "requestedPlanType",
        "reviewUrl",
        "adminDashboardUrl",
      ],
    },
  }),

  // Backward-compatible legacy keys still used by existing routes/tests.
  "order-status-update": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "orders",
    trigger: "Legacy generic status transition notification.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: ["customerName", "orderId", "status", "message", "orderUrl"],
    },
  }),
  "shipment-dispatched": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "shipping",
    trigger: "Legacy shipment-dispatched notification key.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: ["customerName", "orderId", "carrier", "trackingNumber", "trackingUrl", "orderUrl"],
    },
  }),
  "admin-approved-account": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "onboarding",
    trigger: "Legacy approval notification key from admin review flow.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: ["accountName", "loginUrl", "appUrl"],
    },
  }),
  "admin-rejected-account": defineEntry({
    tier: EMAIL_TIERS.TIER_1,
    audience: "customer",
    category: "onboarding",
    trigger: "Legacy rejection notification key from admin review flow.",
    implemented: true,
    live: true,
    payload: {
      required: [],
      optional: ["accountName", "reason", "appUrl"],
    },
  }),

  // Future placeholders retained for prioritization planning.
  "payment-failed-recovery": defineEntry({
    tier: EMAIL_TIERS.TIER_2,
    audience: "customer",
    category: "payments",
    trigger: "Recoverable checkout payment failure with retry path.",
    implemented: false,
    live: false,
    payload: { required: [], optional: [] },
  }),
  "delivery-completed": defineEntry({
    tier: EMAIL_TIERS.TIER_2,
    audience: "customer",
    category: "shipping",
    trigger: "Dedicated delivery completion notification milestone.",
    implemented: false,
    live: false,
    payload: { required: [], optional: [] },
  }),
  "return-accepted": defineEntry({
    tier: EMAIL_TIERS.TIER_2,
    audience: "customer",
    category: "returns",
    trigger: "Return/exchange request accepted.",
    implemented: false,
    live: false,
    payload: { required: [], optional: [] },
  }),
  "refund-initiated": defineEntry({
    tier: EMAIL_TIERS.TIER_2,
    audience: "customer",
    category: "payments",
    trigger: "Separate refund initiation milestone, if introduced.",
    implemented: false,
    live: false,
    payload: { required: [], optional: [] },
  }),
  "application-received": defineEntry({
    tier: EMAIL_TIERS.TIER_2,
    audience: "customer",
    category: "onboarding",
    trigger: "General application receipt milestone.",
    implemented: false,
    live: false,
    payload: { required: [], optional: [] },
  }),
  "review-request": defineEntry({
    tier: EMAIL_TIERS.TIER_3,
    audience: "customer",
    category: "engagement",
    trigger: "Post-purchase review campaign.",
    implemented: false,
    live: false,
    payload: { required: [], optional: [] },
  }),
  "cart-abandonment": defineEntry({
    tier: EMAIL_TIERS.TIER_3,
    audience: "customer",
    category: "marketing",
    trigger: "Abandoned cart reminder.",
    implemented: false,
    live: false,
    payload: { required: [], optional: [] },
  }),
  "back-in-stock": defineEntry({
    tier: EMAIL_TIERS.TIER_3,
    audience: "customer",
    category: "inventory",
    trigger: "Back-in-stock notification.",
    implemented: false,
    live: false,
    payload: { required: [], optional: [] },
  }),
  "artist-newsletter": defineEntry({
    tier: EMAIL_TIERS.TIER_3,
    audience: "customer",
    category: "marketing",
    trigger: "Promo/newsletter campaigns.",
    implemented: false,
    live: false,
    payload: { required: [], optional: [] },
  }),
});

const getTemplateCatalogEntry = (templateKey) =>
  EMAIL_TEMPLATE_CATALOG[String(templateKey || "").trim().toLowerCase()] || null;

const listTemplateKeysByTier = (tier) => {
  const normalizedTier = String(tier || "").trim().toLowerCase();
  return Object.keys(EMAIL_TEMPLATE_CATALOG).filter((key) => {
    return EMAIL_TEMPLATE_CATALOG[key].tier === normalizedTier;
  });
};

module.exports = {
  EMAIL_TIERS,
  EMAIL_TEMPLATE_CATALOG,
  getTemplateCatalogEntry,
  listTemplateKeysByTier,
};
